#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: press-the-button-config
data:
  secretKey: #@ base64.encode("press-the-button-sk-" + data.values.secretKey)
  serverHost: #@ base64.encode(data.values.serverHost)
  backendHost: #@ base64.encode(data.values.backendHost)
  backendPort: #@ base64.encode(data.values.backendPort)
