#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-proxy-for-example-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - image: bitnami/oauth2-proxy:7.3.0
          name: proxy
          ports:
            - containerPort: 4180
              name: proxy-port
              protocol: TCP
          env:
            - name: ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: example-app-client
                  key: issuer-uri
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: example-app-client
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: example-app-client
                  key: client-secret
          command: [ "oauth2-proxy" ]
          args:
            - --oidc-issuer-url=$(ISSUER_URI)
            - --client-id=$(CLIENT_ID)
            - --insecure-oidc-skip-issuer-verification=true
            - --client-secret=$(CLIENT_SECRET)
            - --cookie-secret=0000000000000000
            - --cookie-secure=false
            - --http-address=http://:4180
            - --provider=oidc
            - --scope=openid email profile roles
            - --email-domain=*
            - --insecure-oidc-allow-unverified-email=true
            - --oidc-groups-claim=roles
            - #@ "--upstream=http://example-app.{}".format(data.values.domain)
            - #@ "--redirect-url=http://example-app.{}/callback".format(data.values.domain)
            - --skip-provider-button=false
            - --pass-authorization-header=true
            - --prefer-email-to-user=true

---
apiVersion: v1
kind: Service
metadata:
  name: oauth-proxy-for-example-app
  namespace: apps
spec:
  ports:
    - port: 80
      targetPort: 4180
  selector:
    name: oauth-proxy-for-example-app

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: oauth-proxy-for-example-app
  namespace: apps
spec:
  virtualhost:
    fqdn: #@ "oauth-proxy-for-example-app.{}".format(data.values.domain)
  routes:
    - conditions:
        - prefix: /
      services:
        - name: oauth-proxy-for-example-app
          port: 80
