version: '2.7'
services:
  terraform:
    image: hashicorp/terraform:1.5
    working_dir: /work
    volumes:
      - $PWD:/work
      - tf-data-dir:/data
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION=us-east-2
      - TF_VAR_domain_name=${DOMAIN_NAME}
      - TF_DATA_DIR=/data
  terraform-plan:
    extends: terraform
    command:
      - plan
      - -input=false
  terraform-apply:
    extends: terraform
    command:
      - apply
      - -input=false
      - -auto-approve
      - -compact-warnings
  terraform-output:
    extends: terraform
    command:
      - output
      - -json
volumes:
  tf-config: {}
  tf-data-dir: {}
