SOURCE_IMAGE = os.getenv("SOURCE_IMAGE", default='harbor.platform.sbx.tanzufederal.com/press-the-button-frontend-source')
LOCAL_PATH = os.getenv("LOCAL_PATH", default='.')
NAMESPACE = os.getenv("NAMESPACE", default='default')

k8s_custom_deploy(
    'press-the-button-frontend',
    apply_cmd="tanzu apps workload apply -f workload.yaml --update-strategy replace --debug --live-update" +
              " --local-path " + LOCAL_PATH +
              " --source-image " + SOURCE_IMAGE +
              " --namespace " + NAMESPACE +
              " --yes --output yaml",
    delete_cmd="tanzu apps workload delete -f config/workload.yaml --namespace " + NAMESPACE + " --yes",
    deps=['manage.py', 'press_the_button/'],
    container_selector='workload',
    live_update=[
      sync('./press_the_button','/workspace/press_the_button'),
      sync('./manage.py','/workspace/manage.py')
    ]
)

k8s_resource('press-the-button-frontend', port_forwards=["8080:8080"],
            extra_pod_selectors=[{'carto.run/workload-name': 'press-the-button-frontend','app.kubernetes.io/component': 'run'}])
allow_k8s_contexts(k8s_context())