apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: perform-secrets-scan-yelp
spec:
  description: |-
    Uses Yelp's detect-secrets to scan for commonly-found secrets within source code tracked by a provided Git repository.
  params:
  - name: git_blob_url
  - name: git_blob_ref
  results:
  - name: provided_git_url
  - name: provided_git_ref
  - name: scan-log
    description: The log that ZAP produced during the scan.
  - name: scan-result
    description: The result of the ZAP scan.
    type: string
  steps:
  # output-repo-properties is needed so that the
  # ClusterSourceTemplate that calls this task can re-retrieve the 
  - image: bash:5
    name: output-repo-properties
    script: |
      #!/usr/bin/env bash
      tr -d '\n' <<< $(params.git_blob_url) > $(results.provided_git_url.path)
      tr -d '\n' <<< $(params.git_blob_ref) > $(results.provided_git_ref.path)
  - image: bash:5
    name: detect-secrets
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      apk add git curl python3 py3-pip jq --no-progress -q

      curl -o /tmp/repo.tar.gz $(params.git_blob_url)
      mkdir /repo && tar -xzf /tmp/repo.tar.gz -C /repo


      # Required to turn off the virtualenv check.
      pip install detect-secrets --break-system-packages
      results=$(detect-secrets -C /repo scan --all-files | jq -r .results)
      if test "$results" == '{}'
      then
        >&2 echo "INFO: No secrets detected!"
        exit 0
      fi
      >&2 echo "ERROR: Secrets scan failed! See results below to see where secrets were found."
      echo "$results"
      exit 1

