apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: perform-secrets-scan-yelp
spec:
  description: |-
    Uses Yelp's detect-secrets to scan for commonly-found secrets within source code tracked by a provided Git repository.
  params:
  - name: git_url
  - name: git_sha
  results:
  - name: provided_git_url
  - name: provided_git_ref
  - name: scan-log
    description: The log that ZAP produced during the scan.
  - name: scan-result
    description: The result of the ZAP scan.
    type: string
  workspaces:
    - name: git_repo
      mountPath: /repo
  steps:
  # output-repo-properties is needed so that the
  # ClusterSourceTemplate that calls this task can re-retrieve the URL and ref and feed it down
  # through the supply chain.
  - image: bash:5
    name: output-repo-url
    script: |
      #!/usr/bin/env bash
      echo $(params.git_url) > $(results.provided_git_url.path)
  - image: bash:5
    name: output-repo-ref
    script: |
      #!/usr/bin/env bash
      echo $(params.git_ref) > $(results.provided_git_ref.path)
  - image: bash:5
    name: clone-the-repository
    script: |
      #!/usr/bin/env bash
      apk add git curl --no-progress -q
      cd /repo
      git clone --branch $(params.git_sha) $(params.git_url)
      ls /repo

