apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-httpproxies
  namespace: apps
rules:
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - get
  - list
