apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-httpproxies-sa
  namespace: apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-httpproxies
subjects:
- kind: ServiceAccount
  name: default
