#@ load("@ytt:data","data")
#@ load("@ytt:base64","base64")
apiVersion: v1
kind: Secret
metadata:
  name: issm-review-github-token
  #@ if data.values.namespace == None:
  namespace: apps
  #@ else:
  namespace: #@ data.values.namespace
  #@ end
data:
  review_github_project: #@ base64.encode(data.values.project_name)
  review_repo_token: #@ base64.encode(data.values.github_token)
  review_repo_username: #@ base64.encode(data.values.github_username)

