apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: raise-dast-template
spec:
  healthRule:
    alwaysHealthy: {}
  lifecycle: tekton
  configPath: .status.template
  ytt: |
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: #@ data.values.workload.metadata.name + "-dast-cm"
    data: {}
