apiVersion: carto.run/v1alpha1
kind: ClusterConfigTemplate
metadata:
  name: raise-image-scanner-template
spec:
  healthRule:
    alwaysHealthy: {}
  lifecycle: tekton
  configPath: .status.template
  ytt: |
    ---
    #@ load("@ytt:data", "data")
    apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        frameworks.doncio.navy.mil/requires-raise: "true"
      name: #@ data.values.workload.metadata.name + "-image-scanner-cm"
    data: {}
