apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: raise-secrets-template
spec:
  healthRule:
    alwaysHealthy: {}
  lifecycle: mutable
  imagePath: .data.image
  ytt: |
    ---
    #@ load("@ytt:data", "data")
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: #@ data.values.workload.metadata.name + "-secrets-cm"
    data:
      image: #@ data.values.image
