apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: raise-secrets-template
spec:
  healthRule:
    alwaysHealthy: {}
  lifecycle: mutable
  urlPath: .status.taskResults[?(@.name=="provided_git_url")].value
  revisionPath: .status.taskResults[?(@.name=="provided_git_ref")].value
  ytt: |
    ---
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: #@ data.values.deliverable.metadata.name + "-secrets-scan"
      labels: #@ merge_labels({ "app.kubernetes.io/component": "deploy" })
    spec:
      runTemplateRef:
        name: tekton-taskrun
      inputs:
        serviceAccount: #@ data.values.params.serviceAccount
        taskRef:
          kind: ClusterTask
          name: perform-secrets-scan-yelp
        params:
          - name: git_url
            value: #@ data.values.source.url
          - name: git_sha
            value: #@ data.values.source.revision
