#@ load("@ytt:data", "data")
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: app-with-bitnami-base-image
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: app-with-bitnami-base-image
spec:
  image: #@ data.values.image_name
