apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: example-customer
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: example-customer
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-java
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: customer-relations-department
        system: profile-management
        description: Manage customer profiles
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: customer-database
